language: java
jdk:
        -openjdk11
        
addons:
    sonarcloud:
        organization: kevinmoreland
        token: faa933391d9046ef54c7736ede494bda36dc8299
script: 
- ant build
- sonar-scanner